/**
 * Standardized Error Codes
 * 
 * All error codes used throughout the application.
 * These codes are used for structured error responses.
 */

export const ERROR_CODES = {
  // Authentication & Authorization
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  AUTH_INVALID_TOKEN: 'AUTH_INVALID_TOKEN',
  AUTH_INVALID_ROLE: 'AUTH_INVALID_ROLE',
  AUTH_MISSING_CLIENT_ID: 'AUTH_MISSING_CLIENT_ID',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',

  // Session Management
  SESSION_NOT_AUTHORIZED: 'SESSION_NOT_AUTHORIZED',
  SESSION_ALREADY_EXISTS: 'SESSION_ALREADY_EXISTS',
  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
  SESSION_INVALID_PAIRING: 'SESSION_INVALID_PAIRING',
  SESSION_TIMEOUT: 'SESSION_TIMEOUT',
  SESSION_KIOSK_OFFLINE: 'SESSION_KIOSK_OFFLINE',

  // Client Registration
  CLIENT_NOT_REGISTERED: 'CLIENT_NOT_REGISTERED',
  CLIENT_ALREADY_REGISTERED: 'CLIENT_ALREADY_REGISTERED',
  CLIENT_NOT_FOUND: 'CLIENT_NOT_FOUND',

  // WebRTC Signaling
  SIGNALING_INVALID_TARGET: 'SIGNALING_INVALID_TARGET',
  SIGNALING_NO_SESSION: 'SIGNALING_NO_SESSION',
  SIGNALING_UNAUTHORIZED_SENDER: 'SIGNALING_UNAUTHORIZED_SENDER',
  SIGNALING_INVALID_PAIRING: 'SIGNALING_INVALID_PAIRING',
  SIGNALING_MISSING_DATA: 'SIGNALING_MISSING_DATA',

  // Crew Events
  CREW_EVENT_INVALID_PAYLOAD: 'CREW_EVENT_INVALID_PAYLOAD',
  CREW_EVENT_RATE_LIMITED: 'CREW_EVENT_RATE_LIMITED',
  CREW_EVENT_UNAUTHORIZED: 'CREW_EVENT_UNAUTHORIZED',

  // Rate Limiting
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',

  // Call Control
  CALL_INVALID_STATE: 'CALL_INVALID_STATE',
  CALL_ALREADY_IN_PROGRESS: 'CALL_ALREADY_IN_PROGRESS',
  CALL_NOT_INITIATED: 'CALL_NOT_INITIATED',
  CALL_REQUEST_FAILED: 'CALL_REQUEST_FAILED',

  // General
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  INVALID_REQUEST: 'INVALID_REQUEST',
  OPERATION_NOT_ALLOWED: 'OPERATION_NOT_ALLOWED'
};